### ISSUE TITLE
Plugin not compatible with idea-2023.1

### ISSUE THREAD

**Issue by mlangc** [By-Ilya/theme-toggler#2]
First & foremost, thanks a lot for your great work!

I just wanted to mention, that the plugin is not compatible with the latest IDEA release. Let me know if you don't have time to look into it - I can try to submit a PR.

**Comment by By-Ilya** [comment]
@mlangc Hi! Thanks a lot for your feedback and noticed issue!

I will fix the issue soon, and will notify you!

**Comment by By-Ilya** [comment]
@mlangc Hi! I have fixed plugin compatibility issue! After updating the gradle and IDEA sandbox versions to the latest, it seems problem was fixed! I have created a PR for it, you can check it.

I also already uploaded the new version of plugin with current fixes (v1.1.1), it should be approved and published by JetBrains team in two business days. When you will able to update to the 1.1.1 version and check that all working fine with new IDEA version, we can close this issue.

Thanks a lot again for complaining about really important issue! 👍

**Comment by mlangc** [comment]
Thank you very much - I'll update as soon as the new version is available and let you know if it works.

**Comment by mlangc** [comment]
Works like a charm :-) - thank you very much!

**Comment by By-Ilya** [comment]
@mlangc Thanks for feedback! :)
