### ISSUE TITLE
Plugin not compatible with IntelliJ IDEA 2023.3

### ISSUE THREAD

**Issue by mlangc** [By-Ilya/theme-toggler#5]
Thanks a lot for the great plugin - it's really useful to me!

Unfortunately I can't use it anymore since updating to IDEA 2023.3 since it's not compatible with this version.

**Comment by bachi76** [comment]
It's a lifesaver, and I even consider stopping IDE updates until this plugin is updated :-)

**Comment by By-Ilya** [comment]
@mlangc and @bachi76 Hello and thanks for providing feedback! I super happy to hear it! :)

Yeah, I noticed incompatibility with 2023.3 a bit later than you, sorry for this! I worked on it the whole previous week, JetBrains changed an API a bit dramatically and it was required to rewrite a lot of stuff to adapt for the new API :)

So, I'm pretty much on the way to finish, merging the changes, double check everything and publishing new 1.2.0 version. Hope it will be available in the next 1-2 days after JetBrains verification!

**Comment by By-Ilya** [comment]
@mlangc and @bachi76 I created a PR for the issue and publish new plugin version 1.2.0. I will wait for the verification, hope it will be published soon.

**Comment by bachi76** [comment]
Thanks a lot for your continued effort @By-Ilya ! Looking forward to get it back working.

**Comment by AyalaMan-Main** [comment]
Hi @By-Ilya , thank you for your plugin, it is really helpful, do you have some news?

Thanks!

**Comment by By-Ilya** [comment]
Hello, @saayalac & @bachi76!
Still fighting with JetBrains, they deprecated some API and functions (so, just because of this plugin became incompatible with newest IDEA version), but new API with which plugin is working normally marked as "Internal" one, which basically means that I can't use it.

I had a chat with a supporter, he wasn't able to find any solution and put my request for developers, still waiting answer from them.

I'm super sorry for such delays with it, I didn't expect, that JetBrains support works slowly

**Comment by By-Ilya** [comment]
@saayalac @mlangc & @bachi76 As alternative (temporary of course) solution for now, I can suppose that I can share here the built plugin file, which I published to JetBrains system, so basically you can install it right now from disk.

Installation process:

1. Go to Settings -> Plugins
2. Click on Gear icon on top -> Install Plugin From Disk
3. Choose .zip file that I attached here (no need to unarchive it, just download and use as it is)
4. Restart IDE
5. Done

![Screenshot 2024-02-01 at 22 36 04](https://github.com/By-Ilya/theme-toggler/assets/19195632/c4b03e0c-4e38-4b22-bdcc-5e970d8fafca)

[theme-switch-1.2.0.zip](https://github.com/By-Ilya/theme-toggler/files/14130778/theme-switch-1.2.0.zip)

---

I will notify you here when something will be clear with JetBrains :) Hope everything will be good with installation plugin from disk.

**Comment by By-Ilya** [comment]
Hello @saayalac @mlangc and @bachi76! Finally today JetBrains approved my plugin, so, I tested, plugin is accessible from IntelliJ Marketplace on last version of IDE!

If you installed the plugin from disk using .zip in my message above, you can freely remove it before and then install from Marketplace!

Enjoy! :)
